language: csharp

addons:
  apt:
    packages:
      - dcraw

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      dotnet: 1.0.0-preview2-003131
      mono: none
      env: CONFIGURATION=Debug FRAMEWORK=netcoreapp1.1 DOTNETCORE=1
    - os: linux
      dist: trusty
      sudo: required
      dotnet: 1.0.0-preview2-003131
      mono: none
      env: CONFIGURATION=Release FRAMEWORK=netcoreapp1.1 DOTNETCORE=1

script:
  - dotnet restore
  - cd src/NDCRaw
  - dotnet build -c $CONFIGURATION -f $FRAMEWORK
  - cd ../../test/NDCRaw.Tests
  - dotnet build -c $CONFIGURATION -f $FRAMEWORK
  - dotnet test -c $CONFIGURATION -f $FRAMEWORK
